spin_version = "1"
authors = ["root"]
description = "foo"
name = "foo"
trigger = { type = "http", base = "/hello" }
version = "0.1.0"

[[component]]
id = "foo"
source = "target/wasm32-wasi/release/foo.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
