# FROM rust:1.61.0 as build

# RUN rustup target add x86_64-unknown-linux-musl
# RUN apt update && apt install -y musl-tools musl-dev

# # create a new empty shell project
# RUN USER=root cargo new --bin hello-docker
# WORKDIR /hello-docker

# # copy over your manifests
# COPY ./Cargo.lock ./Cargo.lock
# COPY ./Cargo.toml ./Cargo.toml

# # this build step will cache your dependencies
# RUN cargo build --target x86_64-unknown-linux-musl --releases
# RUN rm src/*.rs

# # copy your source tree
# COPY ./src ./src

# # build for release
# RUN rm ./target/release/hello-docker*
# RUN cargo build --release

# FROM scratch
# COPY --from=build /hello-docker/target/x86_64-unknown-linux-musl/hello-docker .
# CMD ["./hello-docker"]


# Build Stage
FROM rust:1.61.0 AS builder
WORKDIR /usr/src/
RUN rustup target add x86_64-unknown-linux-musl

RUN USER=root cargo new deciduously-com
WORKDIR /usr/src/deciduously-com
COPY Cargo.toml Cargo.lock ./
RUN cargo build --release

COPY src ./src
# COPY templates ./templates
RUN cargo install --target x86_64-unknown-linux-musl --path .

# Bundle Stage
FROM scratch
COPY --from=builder /usr/local/cargo/bin/deciduously-com .
USER 1000
CMD ["./deciduously-com"]